---
- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  become: true
  
- name: Install required software
  ansible.builtin.apt:
    name:
      - ansible-core
      - docker.io
      - docker-compose
      - docker-buildx
      - make
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
  become: true

- name: Change owner of docker.sock to the user
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: "{{ ansible_user }}"
  become: true

- name: Enable and start docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Install docker buildx
  ansible.builtin.command: docker buildx install
